helio:
  crud:
    # JDBC驱动类名，根据数据库类型自行修改
    db-driver-class: com.mysql.cj.jdbc.Driver
    # 数据库类型
    db-type: mysql
    # 数据库连接主机
    db-host: 127.0.0.1
    # 数据库端口
    db-port: 3306
    # 数据库登录账号
    db-username: root
    # 数据库登录密码
    db-password: root
    # 数据库名
    db-name: helio_boot
  web:
    logging:
      # 是否启用 Web 访问日志切面；开发、测试环境可以开启，生产环境不开启
      enabled: false

spring:
  redis:
    # Redis连接主机
    host: 127.0.0.1
    # Redis连接端口
    port: 6379
    # Redis登录密码
    password:
    # Redis数据库序号
    database: 1

knife4j:
  # 生产环境务必设为true
  production: true

logging:
  level:
    # 指定日志级别，开发、测试环境建议为 DEBUG，生产环境建议为 INFO
    cc.uncarbon: INFO
